/*Pulls horse mussel catches for every tow, even if zero catch but does NOT prorate to 800 m and 17.5 , but does take the catch to being a single 2 foot drag; 
To get whole numbers that show the length frequencies of horse mussels that were caught on the survey, use the data extraction from this SQL, multiple by 2, and remove tows where sum of all length frequency bins = 0 
i.e. remove tows that caught zero horse mussel */
SELECT cruise,
    tow_no,
    tow_type_id,
    mgt_area_id,
    start_lat,
    start_long,
    strata_id,
    depth,
    ROUND(SUM(DECODE(bin_id,0,number_in_bin*NVL(prorate_factor,1)/2, 0) ), 1) bin_id_0,
    ROUND(SUM(DECODE(bin_id,5,number_in_bin*NVL(prorate_factor,1)/2, 0)   ), 1) bin_id_5,
    ROUND(SUM(DECODE(bin_id,10,number_in_bin*NVL(prorate_factor,1)/2, 0)  ), 1) bin_id_10,
    ROUND(SUM(DECODE(bin_id,15,number_in_bin*NVL(prorate_factor,1)/2, 0)   ), 1) bin_id_15,
    ROUND(SUM(DECODE(bin_id,20,number_in_bin*NVL(prorate_factor,1)/2, 0)  ), 1) bin_id_20,
    ROUND(SUM(DECODE(bin_id,25,number_in_bin*NVL(prorate_factor,1)/2, 0)  ), 1) bin_id_25,
    ROUND(SUM(DECODE(bin_id,30,number_in_bin*NVL(prorate_factor,1)/2, 0)   ), 1) bin_id_30,
    ROUND(SUM(DECODE(bin_id,35,number_in_bin*NVL(prorate_factor,1)/2, 0)   ), 1) bin_id_35,
    ROUND(SUM(DECODE(bin_id,40,number_in_bin*NVL(prorate_factor,1)/2, 0)   ), 1) bin_id_40,
    ROUND(SUM(DECODE(bin_id,45,number_in_bin*NVL(prorate_factor,1)/2, 0)   ), 1) bin_id_45,
    ROUND(SUM(DECODE(bin_id,50,number_in_bin*NVL(prorate_factor,1)/2, 0)  ), 1) bin_id_50,
    ROUND(SUM(DECODE(bin_id,55,number_in_bin*NVL(prorate_factor,1)/2, 0)  ), 1) bin_id_55,
    ROUND(SUM(DECODE(bin_id,60,number_in_bin*NVL(prorate_factor,1)/2, 0)   ), 1) bin_id_60,
    ROUND(SUM(DECODE(bin_id,65,number_in_bin*NVL(prorate_factor,1)/2, 0)  ), 1) bin_id_65,
    ROUND(SUM(DECODE(bin_id,70,number_in_bin*NVL(prorate_factor,1)/2, 0)   ), 1) bin_id_70,
    ROUND(SUM(DECODE(bin_id,75,number_in_bin*NVL(prorate_factor,1)/2, 0)  ), 1) bin_id_75,
    ROUND(SUM(DECODE(bin_id,80,number_in_bin*NVL(prorate_factor,1)/2, 0)  ), 1) bin_id_80,
    ROUND(SUM(DECODE(bin_id,85,number_in_bin*NVL(prorate_factor,1)/2, 0)  ), 1) bin_id_85,
    ROUND(SUM(DECODE(bin_id,90,number_in_bin*NVL(prorate_factor,1)/2, 0)  ), 1) bin_id_90,
    ROUND(SUM(DECODE(bin_id,95,number_in_bin*NVL(prorate_factor,1)/2, 0)  ), 1) bin_id_95,
    ROUND(SUM(DECODE(bin_id,100,number_in_bin*NVL(prorate_factor,1)/2, 0)  ), 1) bin_id_100,
    ROUND(SUM(DECODE(bin_id,105,number_in_bin*NVL(prorate_factor,1)/2, 0)  ), 1) bin_id_105,
    ROUND(SUM(DECODE(bin_id,110,number_in_bin*NVL(prorate_factor,1)/2, 0)  ), 1) bin_id_110,
    ROUND(SUM(DECODE(bin_id,115,number_in_bin*NVL(prorate_factor,1)/2, 0)   ), 1) bin_id_115,
    ROUND(SUM(DECODE(bin_id,120,number_in_bin*NVL(prorate_factor,1)/2, 0)  ), 1) bin_id_120,
    ROUND(SUM(DECODE(bin_id,125,number_in_bin*NVL(prorate_factor,1)/2, 0)  ), 1) bin_id_125,
    ROUND(SUM(DECODE(bin_id,130,number_in_bin*NVL(prorate_factor,1)/2, 0)  ), 1) bin_id_130,
    ROUND(SUM(DECODE(bin_id,135,number_in_bin*NVL(prorate_factor,1)/2, 0)  ), 1) bin_id_135,
    ROUND(SUM(DECODE(bin_id,140,number_in_bin*NVL(prorate_factor,1)/2, 0)   ), 1) bin_id_140,
    ROUND(SUM(DECODE(bin_id,145,number_in_bin*NVL(prorate_factor,1)/2, 0)  ), 1) bin_id_145,
    ROUND(SUM(DECODE(bin_id,150,number_in_bin*NVL(prorate_factor,1)/2, 0)  ), 1) bin_id_150,
    ROUND(SUM(DECODE(bin_id,155,number_in_bin*NVL(prorate_factor,1)/2, 0)  ), 1) bin_id_155,
    ROUND(SUM(DECODE(bin_id,160,number_in_bin*NVL(prorate_factor,1)/2, 0)  ), 1) bin_id_160,
    ROUND(SUM(DECODE(bin_id,165,number_in_bin*NVL(prorate_factor,1)/2, 0)  ), 1) bin_id_165,
    ROUND(SUM(DECODE(bin_id,170,number_in_bin*NVL(prorate_factor,1)/2, 0)  ), 1) bin_id_170,
    ROUND(SUM(DECODE(bin_id,175,number_in_bin*NVL(prorate_factor,1)/2, 0)  ), 1) bin_id_175,
    ROUND(SUM(DECODE(bin_id,180,number_in_bin*NVL(prorate_factor,1)/2, 0)  ), 1) bin_id_180,
    ROUND(SUM(DECODE(bin_id,185,number_in_bin*NVL(prorate_factor,1)/2, 0)  ), 1) bin_id_185,
    ROUND(SUM(DECODE(bin_id,190,number_in_bin*NVL(prorate_factor,1)/2, 0)  ), 1) bin_id_190,
    ROUND(SUM(DECODE(bin_id,195,number_in_bin*NVL(prorate_factor,1)/2, 0)  ), 1) bin_id_195
  FROM scbycatchlengthfrequencies l, 
    scbycatches bc,
    (SELECT cruise, tow_no, tow_seq, tow_type_id, mgt_area_id,
    start_lat, start_long,strata_id,depth, drag_width, tow_len 
    FROM sctows 
   WHERE cruise IN (SELECT distinct cruise from sctows WHERE tow_seq IN (SELECT distinct tow_seq from scbycatches WHERE speccd_id = 4332 ))) t
  WHERE l.bycatch_seq(+) = bc.bycatch_seq
  AND t.tow_seq  = bc.tow_seq(+)
  AND l.live_id (+)= 'L'
  GROUP BY cruise,
    tow_no,
    tow_type_id,
    mgt_area_id,
    start_lat,
    start_long,
    strata_id,
    depth,
    tow_len,
    drag_width 
    ORDER BY cruise, tow_no;